apiVersion: v1
kind: ReplicationController
metadata:
  name: web-fe-rc-2
spec:
  replicas: 2 
  selector:
    app: app02-web
  template:
    metadata:
      name: web-fe-pod
      labels:
        app: app02-web
    spec:
      containers:
      - name: web-fe
        image: nginxdemos/hello #just a hello world with host name & ip
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      nodeSelector:
        nodegroup: "0" #Select node group that has Azure LB or ilb assigned to it

# you can also use node affinity http://kubernetes.io/docs/user-guide/node-selection/	alpha feature in kubernetes 1.2. (template installes 1.2.4)